version: '3'

services:
  mongodb-container:
    image: mongo:latest
    restart: always
    networks:
      - mongo-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword

  mongo-express-container:
    depends_on:
      - mongodb-container
    image: mongo-express:latest
    restart: always
    networks:
      - mongo-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      ME_CONFIG_MONGODB_SERVER: mongodb-container

networks:
  mongo-network:
    driver: bridge
