# These environment credentials are just placeholders
# Please configure your server credentials with best practices
version: '3.5'

services:
  mongodb-container:
    image: mongo:latest
    restart: always
    networks:
      - mongo-network
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}

  mongo-express-container:
    depends_on:
      - mongodb-container
    image: mongo-express:latest
    restart: always
    networks:
      - mongo-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_SERVER}

networks:
  mongo-network:
    driver: bridge
